services:
  - type: web
    name: crimedjango
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn CrimeTrack.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CrimeTrack.settings
